### PR TITLE
Ignore dist folder

### PR DESCRIPTION
**Pull request by justinforce**
This'll keep from dirtying the repository when the Haskell implementation is compiled.

### CODE REVIEW

**Comment by zhimsel** [comment]
Duplicate of #61

**Comment by justinforce** [comment]
Is it? The dist folder was the only untracked file created when I built the Haskell bin. The other 15 lines seen superfluous. Am I missing something?

**Comment by zhimsel** [comment]
The functionality created here is duplicated by the functionality of #61. Sure, they can operate independently, but there's also no reason to have both.

**Comment by justinforce** [comment]
@zhimsel Right. My point is that you're using 16 lines to do the work that can be done by 1 line. You don't need to enumerate all of those types. All generated files that need to be ignored are in the `dist` path. You only need to ignore `dist`.

**Comment by zhimsel** [comment]
Fair enough. I'll close mine.

**Comment by olivierverdier** [comment]
This is no longer necessary as we use stack now instead (b243027a09d993b207c340633cfebd87ade787dd). There are now some relevant ignored folder in `.gitignore`.

**Pull request closed without merging**
